---
- name: Build and run Next.js Docker image on remote Docker server
  hosts: docker-server
  become: yes
  tasks:

    - name: Copy Next.js app source to Docker server
      synchronize:
        src: "/opt/docker/nextjs-docker-ansible/.."
        dest: /opt/mynext-app
        delete: yes
      delegate_to: localhost

    - name: Build Docker image on remote Docker server
      community.docker.docker_image:
        name: nextjs-app
        tag: latest
        source: build
        state: present
        build:
          path: /opt/mynext-app
          dockerfile: Dockerfile

    - name: Run Docker container
      community.docker.docker_container:
        name: nextjs-app
        image: nextjs-app:latest
        published_ports:
          - "3000:3000"
        restart_policy: always
        state: started
        
    - name: Remove dangling images
      community.docker.docker_prune:
        images: yes
